apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: trace-netcat-execve
spec:
  kprobes:
    - call: "__x64_sys_execve"
      syscall: true
      #return: false
      args:
        - index: 0
          type: string
      selectors:
      - matchArgs:
        - index: 0
          operator: "Equal"
          values:
          - "/usr/bin/netcat"
        matchActions:
        - action: Sigkill
